### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by bbrown** [markuslindenberg/nginx_request_exporter#1]
When I try to install via `go get` I get the following error:

`go/src/github.com/markuslindenberg/nginx_request_exporter/nginx_request_exporter.go:120: undefined: prometheus.RegisterOrGet`

It looks like the current Prometheus client has [removed](https://godoc.org/github.com/prometheus/client_golang/prometheus#Register) the deprecated RegisterOrGet function. I would fix it and submit a PR but I don't know golang.

(I tried monkeying around with the obvious things but just dug myself a deeper hole.)

**Comment by markuslindenberg** [comment]
Thanks for the pull request, fixed.
